<?php
/** @var $block Image */

/** @var $escaper Escaper */

use Magento\Catalog\Block\Product\Image;
use Magento\Framework\Escaper;

?>
<img class="photo image lazy_load ?>"
<?php foreach ($block->getCustomAttributes() as $name => $value): ?>
<?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtml($value) ?>"
<?php endforeach; ?>
data-original="<?= /* @escapeNotVerified */ $block->getImageUrl(); ?>"
src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magento_LazyLoad::images/Loading.gif')) ?>"
loading="lazy"
width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>" />
