<?php
/** @var $block Image */
/** @var $escaper Escaper */
/** @var SecureHtmlRenderer $secureRenderer */

use Magento\Catalog\Block\Product\Image;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

$width = (int)$block->getWidth();
$paddingBottom = $block->getRatio() * 100;
?>
<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?>">
    <span class="product-image-wrapper">
        <img class="photo image lazy_load"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtml($value) ?>"
            <?php endforeach; ?>
            data-original="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
            src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('Magento_LazyLoad::images/Loading.gif') ?>"
            loading="lazy"
            width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
            height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
            alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"/></span>
</span>
